### ISSUE TITLE
Black interface

### ISSUE THREAD

**Issue by KatanaO** [hiddify/hiddify-next#1057]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

i'm using portable version of Hiddify on win11... when program starts, only opens a whole black windows. This happens in recent updated versions (1.6.1 to 1.6.3). and everything is normal with previous versions like 1.6.0dev and before when i use them.

### Minimal Reproducible Example (MRE)

nothing

### Version

1.6.3

### Platform/OS

Windows

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hiddify-com** [comment]
Please provide more information about your OS

**Comment by KatanaO** [comment]
Processor	Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz   3.10 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	22H2
OS build	22621.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0

This is my current OS info... the problem is just Black window, cause when i move mouse on this black windows it seems i can click on that part menu and option, but like on a hidden text and menu. It happens on 1.6.1 ver and the next... Then i roll back to the correct verion (1.6.0dev) that has no problem like described above.

**Comment by KatanaO** [comment]
> temporary fix : close app remove this file : "AppData\Roaming\Hiddify\hiddify\shared_preferences.json" open app

tx, but no change and fix  :|

**Comment by emperor-2025** [comment]
win11系统同样的便携版问题一样界面没有任何按钮和图标。

**Comment by pranjbar1** [comment]
> remove this file : "AppData\Roaming\Hiddify\hiddify\shared_preferences.json"

I did it and deleted the file, but the problem is still there

**Comment by ZeroNilZero** [comment]
Same problem on Ubuntu 24.04.

Solution: Right-click the Hiddify icon and select "Launch using Discrete Graphics Card." This should resolve the issue.

**Comment by adslyear** [comment]
`21:32:01.490844 - [I] AutoStartNotifier: auto start is [Disabled]
21:32:01.490844 - [D] bootstrap: [auto start service] initialized in 0ms
21:32:01.490844 - [I] bootstrap: initializing [logs repository]
21:32:01.497847 - [D] bootstrap: [logs repository] initialized in 6ms
21:32:01.497847 - [I] bootstrap: initializing [logger controller]
21:32:01.497847 - [I] bootstrap: hiddify v2.1.1 (20101) [prod]
general release
windows ["Windows 10 IoT Enterprise" 10.0 (Build 19045)]
21:32:01.497847 - [I] bootstrap: initializing [profile repository]
21:32:01.500844 - [I] bootstrap: initializing [active profile]
21:32:02.487845 - [I] bootstrap: initializing [deep link service]
21:32:02.490846 - [I] bootstrap: initializing [sing-box]
21:32:02.491843 - [I] bootstrap: initializing [system tray]
21:32:02.523843 - [I] ConnectionNotifier: connection status: DISCONNECTED
21:32:02.525845 - [I] bootstrap: bootstrap took [1197ms]
21:32:02.677844 - [W] IntroPage: Could not get the local country code based on timezone
MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_timezone)`

`{"flutter.preferences_version":1,"flutter.region":"cn","flutter.locale":"zhCn"}`

install system english version .then change to chinese 
run hiddify only display blackboard
`close app remove this file : "AppData\Roaming\Hiddify\hiddify\shared_preferences.json" open app` 
is the same

**Comment by VitaliiEv** [comment]
Running Hiddify AppImage on Gentoo Linux
`/home/${USER}/.local/share/app.hiddify.com/shared_preferences.json` doesn't solve poblem
Removing `/home/${USER}/.local/share/app.hiddify.com/` also doesn't solve problem

Problem occured after upgrading `mesa` to version 24.2.* as I mentioned in #1334 

Are there any other possible solutions?

**Comment by BoxFoxCB** [comment]
the same situation, black screen when starting. Latest version of the program.
win10

**Comment by KatanaO** [comment]
> Please provide more information about your OS

Hi, same problem with "karing" project fixed with below changes in their last update

-Flutter update
windows/android 3.22.3->3.24.3
ios/macos 3.24.0->3.24.3

Then, Please if possible, take action  :)

**Comment by BoxFoxCB** [comment]
>  Intel Core i5-3570 Ivy Bridge LGA1155, 4 x 3400 МГц
> Installed RAM 4.00 GB
> System type 64-bit operating system, x64-based processor
> Edition Windows 10 Experience 
> Version 21H2

**Comment by rtmreza** [comment]
سلام یادمه 2 ماه پیش گزارش داده بودم  امروز اخرین ورژن رو به امید اینکه درست کردید دانلود کردم و نصب کردم باز هم همچنان صفحه سیاه هست

**Comment by BoxFoxCB** [comment]
> سلام یادمه 2 ماه پیش گزارش داده بودم امروز اخرین ورژن رو به امید اینکه درست کردید دانلود کردم و نصب کردم باز هم همچنان صفحه سیاه هست

download ver. 0.6.0. or 1.6.0.

**Comment by rtmreza** [comment]
> > سلام یادمه 2 ماه پیش گزارش داده بودم امروز اخرین ورژن رو به امید اینکه درست کردید دانلود کردم و نصب کردم باز هم همچنان صفحه سیاه هست
> 
> download ver. 0.6.0. or 1.6.0.

خودم ورژن 1.5.2 دارم که فقط این سالمه   ولی مشکل این ورژن قدیمی ها اینه  که بعضی کانفینگ های هایدفای جدید رو این ورژها کار نمیکنه  و حداقل  ورژن  2.1.5  لازمه

**Comment by apatieh** [comment]
I have the exact same issue but it sounds no one cares

**Comment by lufog** [comment]
I built the program with updated Flutter (3.24.4) and dependencies (`flutter pub upgrade`). Which fixed the black UI problem. Built for Windows 64-bit: https://mega.nz/file/A4pj0Rwa#vhGO_rs_xnK0bH9HNfF6M1ldNKfdf4I0xCsufNyOmhU

**Comment by rtmreza** [comment]
> I built the program with updated Flutter (3.24.4) and dependencies (`flutter pub upgrade`). Which fixed the black UI problem. Built the `main` branch [4d12c86](https://github.com/hiddify/hiddify-app/commit/4d12c860f7f5cdc86eb52e7a5bdd936f36dd07ac) (not the release), for Windows 64-bit. https://mega.nz/file/A4pj0Rwa#vhGO_rs_xnK0bH9HNfF6M1ldNKfdf4I0xCsufNyOmhU (external file exchanger because zip does not fit into the attachment size limit, and 7zip cannot be attached to a message.)

**Thanks man    its worked for me**

**Comment by BoxFoxCB** [comment]
which version runs on win7 64bit?

**Comment by lufog** [comment]
> which version runs on win7 64bit?

As far as I understand, the version of Hiddify I built didn't work for you? Apparently due to the fact that I used Visual Studio 2022. Are the latest official builds working for you (not counting the black screen)? If so, I can try to build you the same version (with updated Flutter), but built in Visual Studio 2019.

**Comment by kumagaya68** [comment]
> I built the program with updated Flutter (3.24.4) and dependencies (`flutter pub upgrade`). Which fixed the black UI problem. Built the `main` branch [4d12c86](https://github.com/hiddify/hiddify-app/commit/4d12c860f7f5cdc86eb52e7a5bdd936f36dd07ac) (not the release), for Windows 64-bit. https://mega.nz/file/A4pj0Rwa#vhGO_rs_xnK0bH9HNfF6M1ldNKfdf4I0xCsufNyOmhU (external file exchanger because zip does not fit into the attachment size limit, and 7zip cannot be attached to a message.)

Thanks, this solved the black screen problem. Do you have version 2.0.5? 2.5.7 doesn't work very well.

**Comment by kumagaya68** [comment]
![snap496](https://github.com/user-attachments/assets/5d76d0cd-36f7-41c6-968c-2ecef0f8981f)
2.5.7 تایم اوت را نشان می دهد، 2.0.5 حالت عادی را نشان می دهد، اگرچه 2.5.7 زمان پایان را نشان می دهد، هنوز قابل دسترسی است.

**Comment by lufog** [comment]
@kumagaya68, sorry, somehow I missed the notification of your comment.
>Do you have version 2.0.5? 2.5.7 doesn't work very well.

No, I only built the last one.

>2.5.7 shows timeout, 2.0.5 shows normal, although 2.5.7 shows timeout, it is still accessible.

I also experience similar behavior, but only on some servers.  I can't say that this behavior prevents me from using the program.

**Comment by burunduchok2000** [comment]
Столкнулся с такой же проблемой. 
Мой конфиг:
Windows 10 Pro 22H2
Intel(R) Core(TM) i3-7300 CPU @ 4.00GHz   4.00 GHz
NVIDIA GeForce GTX 260 (9.18.13.4174)
Решил проблему удалением видео драйвера. На стоковом драйвере все ок.

**Comment by lufog** [comment]
@JoeButtons try [this one](https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2473144601).

**Comment by arseniy2f** [comment]
Драйвера переустанавливал, файл удалял версию старую скачивал не помогает

**Comment by arseniy2f** [comment]
> > Переустанавливал драйверы, удалял файл, скачивал старую версию — не помогает
> 
> Чёрный квадрат вместо пользовательского интерфейса — это ошибка Flutter, которая появляется на некоторых устройствах. Эта ошибка была исправлена во Flutter давным-давно. Я не знаю, почему автор задерживает выпуск новой версии hiddify с обновлёнными зависимостями. До выхода новой версии вы можете использовать [эту исправленную сборку](https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2473144601).

НЕ РАБОТАЕТ

**Comment by arseniy2f** [comment]
> > Переустанавливал драйверы, удалял файл, скачивал старую версию — не помогает
> 
> Чёрный квадрат вместо пользовательского интерфейса — это ошибка Flutter, которая появляется на некоторых устройствах. Эта ошибка была исправлена во Flutter давным-давно. Я не знаю, почему автор задерживает выпуск новой версии hiddify с обновлёнными зависимостями. До выхода новой версии вы можете использовать [эту исправленную сборку](https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2473144601).

в этом и проблема что бы я не менял и не скачивал черный/белый экран всегда

**Comment by zigzag-way** [comment]
> > > Переустанавливал драйверы, удалял файл, скачивал старую версию — не помогает
> > 
> > 
> > Чёрный квадрат вместо пользовательского интерфейса — это ошибка Flutter, которая появляется на некоторых устройствах. Эта ошибка была исправлена во Flutter давным-давно. Я не знаю, почему автор задерживает выпуск новой версии hiddify с обновлёнными зависимостями. До выхода новой версии вы можете использовать [эту исправленную сборку](https://github.com/hiddify/hiddify-app/issues/1057#issuecomment-2473144601).
> 
> в этом и проблема что бы я не менял и не скачивал черный/белый экран всегда

У меня так же

**Comment by zigzag-way** [comment]
> Проблема в драйверах на старые видеокарты nvidia. За amd не скажу, не использовал. Я пытался обновить его на версию посвежее, но она не встает, возможно если править конфиги, что-то и получится принудительно поставить. Но я пошел другим путем. Я удалил устройство вместе с драйвером из диспетчера устройств. Потом обновил кнопкой конфигурацию, и windows сама поставила стандартный майкрософт драйвер. С ним все работает. Я настроил приложение и проверил, что все работает. После этого поставил обратно самый последний драйвер для моей видеокарты с сайта nvidia. И появилось опять черное окно в приложении. Но его можно запускать и отключать, через значок в трее, правой кнопкой мыши. Так и пользуюсь. Если понадобится что-то исправить в конфигурации приложения, придется опять морочиться с удалением драйвера.

У меня AMD. Причем что интересно, с первой попытки (как скачал и поставил) все сразу заработало, после последнего обновления Win11 сегодня работать перестало. Конфиги удалял полностью. Безрезультатно.

**Comment by alexandrzakat** [comment]
> Проблема в драйверах на старые видеокарты nvidia. За amd не скажу, не использовал. Я пытался обновить его на версию посвежее, но она не встает, возможно если править конфиги, что-то и получится принудительно поставить. Но я пошел другим путем. Я удалил устройство вместе с драйвером из диспетчера устройств. Потом обновил кнопкой конфигурацию, и windows сама поставила стандартный майкрософт драйвер. С ним все работает. Я настроил приложение и проверил, что все работает. После этого поставил обратно самый последний драйвер для моей видеокарты с сайта nvidia. И появилось опять черное окно в приложении. Но его можно запускать и отключать, через значок в трее, правой кнопкой мыши. Так и пользуюсь. Если понадобится что-то исправить в конфигурации приложения, придется опять морочиться с удалением драйвера.

тоже с драйвером и старой картой проблема оказалась, карта 9800 nvidia, драйвер 342.01, windows 10 64bit
сделал проще, не через стандартный драйвер, а через безопасный режим, хотя в нем тоже стандартный драйвер и грузится)
Пуск - зажать Shift, а затем нажмите "Перезагрузка". После перезагрузки "Устранение неполадок" -> "Дополнительные параметры" -> "Параметры загрузки" -> "Перезагрузить". Выбрать нужный вариант безопасного режима после перезагрузки. Выбирал F5
Hiddify запустился, добавил конфиг, и еще! при закрытии приложения выбрал "скрывать" и "запомнить выбор"
теперь из нормального режима запустив приложении и закрыв его, оно остается в трее, из него уже подключаю/отключаю

**Comment by DaneshCode** [comment]
> I built the program with updated Flutter (3.24.4) and dependencies (`flutter pub upgrade`). Which fixed the black UI problem. Built the `main` branch [4d12c86](https://github.com/hiddify/hiddify-app/commit/4d12c860f7f5cdc86eb52e7a5bdd936f36dd07ac) (not the release), for Windows 64-bit. https://mega.nz/file/A4pj0Rwa#vhGO_rs_xnK0bH9HNfF6M1ldNKfdf4I0xCsufNyOmhU (external file exchanger because zip does not fit into the attachment size limit, and 7zip cannot be attached to a message.)

If possible, please solve this problem for version 4, which has just been released. Thank you very much.
