### ISSUE TITLE
set system proxy fails

### ISSUE THREAD

**Issue by hadifarnoud** [hiddify/hiddify-next#1061]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When I turn on the VPN, it fails with this error:
Unexpected Error
initialize inbound/mixed [mixed-in]: set system proxy: execute (/usr/ sbin/networksetup) networksetup -setsocksfirewallproxy Wi-Fi
127.0.0.1 2334: exit status 14
<img width="543" alt="Screenshot 2024-07-15 at 13 00 23" src="https://github.com/user-attachments/assets/8c51e983-dbea-4a52-a5ed-b85dd278e818">

### Minimal Reproducible Example (MRE)

1. Open Hiddify
2. Click on big H button
3. got the error

### Version

v1.5.2

### Platform/OS

macOS

### Additional Context

I did remove all proxy and even Hiddify-next app completely and clean installed it. still same issue.

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by realamirhe** [comment]
https://github.com/hiddify/hiddify-next/issues/156
https://github.com/hiddify/hiddify-next/issues/543
https://github.com/hiddify/hiddify-next/issues/869
https://github.com/hiddify/hiddify-next/issues/1052
https://github.com/hiddify/hiddify-next/issues/1061

**Comment by Giant-Li** [comment]
Exactly the same here.
I have a PC running Hackintosh Ventura with a usb Wi-Fi dongle.
Hiddify 2.0.5
Profiles can be imported properly, but error prompted once click the H button

**Comment by Giant-Li** [comment]
Exactly the same here.
I have a PC running Hackintosh Ventura with a usb Wi-Fi dongle.
Hiddify 2.0.5
Profiles can be imported properly, but error prompted once click the H button, then the button turned red

**Comment by lyf571321556** [comment]
the same here.
Hiddify 2.0.5

**Comment by Taneros** [comment]
> the same here. Hiddify 2.0.5

has it been solved in any pre-release versions?

I have this on mac version 12.7.5 (21H1222)

**Comment by Giant-Li** [comment]
I solved the problem according to this thread. https://github.com/hiddify/hiddify-next/issues/869#issuecomment-2323701758

**Comment by To-Azamat** [comment]
On latest pre-release 2.5.7, the problem still there. 
Permissions issue, it fails as regular user but is fine as admin.
