### ISSUE TITLE
Unable to use VPN mode on MacOS

### ISSUE THREAD

**Issue by SaeeSaadat** [hiddify/hiddify-next#187]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

After changing the Config Options to use VPN as service mode, when turning it on this error pops up: 
```
Missing Privilege
VPN mode requires administrator privileges ....
```

I tried opening it using `sudo` or lunching with holding `control` but nothing worked.

### Reproduce the Bug

** On Mac **
Go to Settings
Go to Config Options
select Service Mode
select VPN
Go to Home and turn it on

### Version

0.11.0

### Platform/OS

macOS

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Shellgate** [comment]
روی اندروید هم با کلاینت جدید نمیشه وصل شد

**Comment by linzzzzllll** [comment]
在 2022 m1macbookair 上不起作用,

**Comment by shigomany** [comment]
Same issue

**Comment by lilcheti** [comment]
Same I even tried to run it as sudo but still nothing! The tun mode won't start

**Comment by mrjavadseydi** [comment]
I'm not sure this is a good thing or not but, for using vpn mode in mac os you can use this command :
`sudo "/Applications/Hiddify Next.app/Contents/MacOS/Hiddify Next"`
**Execute this command at your own risk**
 @hiddify-com  if this command is not allowed please let me know

**Comment by codingiran** [comment]
Hiddify Next should consider altering the implementation of administrator privileges. Running an app with sudo in macOS seems unconventional; instead, utilizing a privileges helper is a more standard approach. Please refer to [SMJobBless](https://developer.apple.com/documentation/servicemanagement/1431078-smjobbless) or [SMAppService](https://developer.apple.com/documentation/servicemanagement/smappservice) for guidance.

**Comment by lymanjre** [comment]
This issue is fixed. Pls update your app

**Comment by sghiaseddin** [comment]
> This issue is fixed. Pls update your app

Dear, 
I'm using v0.14.20 and the issue still exists. The solution by mrjavadseydi is working for me:

> I'm not sure this is a good thing or not but, for using vpn mode in mac os you can use this command : `sudo "/Applications/Hiddify Next.app/Contents/MacOS/Hiddify Next"` **Execute this command at your own risk** @hiddify-com if this command is not allowed please let me know

**Comment by rusmux** [comment]
The issue exists in versions v0.14.20 and v0.16.0.dev

**Comment by luxeven** [comment]
v1.1.1仍然存在该问题。MacOS14.1.1中无法获取权限

**Comment by Eden0108** [comment]
v1.1.1 still has this problem.

**Comment by imohammad74** [comment]
in the v1.1.1 still has this problem

**Comment by rwenzlofsky** [comment]
I still have this problem with version 1.1.1

**Comment by s4kharitonov** [comment]
The same problem with version 2.0.5

**Comment by coloneltorchere** [comment]
Any updates on this?

**Comment by github-office** [comment]
2.1.5，the same  problem

**Comment by test-dev24** [comment]
2.2.0, the same problem

**Comment by justMikhail** [comment]
2.0.5，the same problem

**Comment by qtervi** [comment]
v2.3.1, still cannot gain admin rights to run in VPN mode

**Comment by twitch192** [comment]
UP 2.0.5 same

**Comment by hiddify-com** [comment]
use ios version

**Comment by KREeDo5** [comment]
- Open app "Automator" (default app)
- Choose document type: Programm
- Press Library -> Utils 
- Move "Run AppleScript" to workspace

Your code:
```
on run {input, parameters}
	
	(* Your script goes here *)
	
	return input
end run
```

Paste script:
```
do shell script "/Applications/Hiddify.app/Contents/MacOS/Hiddify" with administrator privileges
```

Save as app. GL.

**Comment by Oleg-Perevyshin** [comment]
2.5.7 The problem is present!
Mac mini M1

**Comment by rasdotsu** [comment]
2.5.7 same, macbook pro intel

V2box works excellent and not ask admin rights, maybe look like they did?

**Comment by gunnernn** [comment]
same issue on Windows 11

**Comment by MobinAskari** [comment]
Same issue on Linux Mint v21.3 & Hiddify v2.0.5
"VPN service" or "VPN" modes don't work but "System Proxy" works flawlessly.
I don't have this issue on Windows 11 though

**Comment by agn-7** [comment]
I have the same issue on mac, in the version 2.0.5. but in linux (ubuntu), I bypass this issue by running the app using `sudo`.
But I don't know how would it possible on mac. I also tried `sudo open -a Hiddify` but didn't work eaither.

**Comment by rusmux** [comment]
@agn-7 I do:

```shell
sudo -v
nohup sudo "/Applications/Hiddify.app/Contents/MacOS/Hiddify" > /dev/null &
```

And just close terminal

**Comment by agn-7** [comment]
@rusmux Thank you, it worked.
Now I can activate the VPN mode on Mac as well.

**Comment by katzebue** [comment]
How I made Hiddify auto-start without asking for my password:

**1. Allowed sudo without password for just the Hiddify binary.**

In Terminal, I ran: `sudo visudo`

Then added this line at the bottom (replacing your_username with your Mac username):
`your_username ALL=(ALL) NOPASSWD: /Applications/Hiddify.app/Contents/MacOS/Hiddify`

**2. Created a LaunchAgent to auto-start it on login.**

```sh
mkdir -p ~/Library/LaunchAgents
nano ~/Library/LaunchAgents/com.user.hiddify.plist
```

And pasted this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.user.hiddify</string>

    <key>ProgramArguments</key>
    <array>
      <string>sudo</string>
      <string>/Applications/Hiddify.app/Contents/MacOS/Hiddify</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>StandardOutPath</key>
    <string>/tmp/hiddify.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/hiddify.err</string>
  </dict>
</plist>
```

**3. Loaded it so it runs on login:**
`launchctl load ~/Library/LaunchAgents/com.user.hiddify.plist`

Now you can select VPN mode.
Still waiting for them to add auto-connect though 😅

**Comment by difhel** [comment]
@lymanjre, this issue remains unresolved, forcing users to rely on dubious, unsafe scripts to safeguard their identity and anonymity online. If the System Proxy mode is leaking real IP addresses, it not only makes Discord unusable but also endangers users in third-world countries trying to access these resources.

Please consider looking into this—it's a serious issue. Thanks for your work.

**Comment by Git-I985** [comment]
MacOS has  access rights system and an API to it, developers should rely on this, not `sudo`, `sudo` is not safe. 

**Guys i would recommend you to choose another client. What developers are asking you to do is unsafe and creates risks for attacks.**

**Comment by obergodmar** [comment]
Alternatively, you can download the Hiddify app from the App Store (it is for iOS and iPad). Since most mobile apps also work on macOS, this one runs perfectly fine - you can switch between proxy and VPN modes in the app, and the VPN works through the system VPN profile, so there’s no need to run anything with sudo.

**Comment by TheGP** [comment]
Why the issue is not resolved for so long? There are no people on the team not using Mac?

**Comment by dostapn** [comment]
still unable to use on macos
`hiddify 2.0.5`

**Comment by Treata11** [comment]
Is this an issue related to flutter or it's Apple's fault?
Why is the issue closed by the way?

**Comment by pooryadb** [comment]
I still have this problem
`v 2.5.7`, `macos 26.1`

**Comment by lzskyline** [comment]
same issue

**Comment by DZamataev** [comment]
As a workaround you can use Automator app to create application that runs the following Apple Script and save it as Hiddify Root.app in your applications folder.
```
do shell script "/Applications/Hiddify.app/Contents/MacOS/Hiddify" with administrator privileges
```
That will result in sudo password being requested on launch and VPN mode will work just fine. BTW Hiddify version 4.1.1 (still has the issue).

**Comment by angelo-chan** [comment]
same issue with version 4.1.1 on mac m4

**Comment by hobbes3** [comment]
> As a workaround you can use Automator app to create application that runs the following Apple Script and save it as Hiddify Root.app in your applications folder.
> 
> ```
> do shell script "/Applications/Hiddify.app/Contents/MacOS/Hiddify" with administrator privileges
> ```
> 
> That will result in sudo password being requested on launch and VPN mode will work just fine. BTW Hiddify version 4.1.1 (still has the issue).

I tried messing around with a few variation of the AppleScript command with `sudo -E`, `sudo HOME=/Users/hobbes3`, and `sudo launchctl asuser $(id -u)` and none of them worked. The app will launch without a menu icon and I couldn't load any subs or start any services (proxies nor VPN).

**Comment by hobbes3** [comment]
> Alternatively, you can download the Hiddify app from the App Store (it is for iOS and iPad). Since most mobile apps also work on macOS, this one runs perfectly fine - you can switch between proxy and VPN modes in the app, and the VPN works through the system VPN profile, so there’s no need to run anything with sudo.

This is the only solution that worked for me! Even though it runs as an iPad app, it correctly sets the VPN as a system settings and run without any `sudo` or other hacks (like creating an Automator wrapper).

The only con I see is that the app doesn't show up in the menubar, so it's harder to tell the VPN is running or not. Quitting the app still keeps the VPN running.

<img width="504" height="230" alt="Image" src="https://github.com/user-attachments/assets/79c50e2e-d219-4a6e-96d0-78856a7b6305" />

EDIT: Actually, I ended up just using v2rayN for macOS (and PC) too. It's way more powerful (and a higher learning curve, of course). Hiddify is fine on iOS though, but I'm not sure how good the China whitelist is though.

**Comment by Slade47** [comment]
I can launch the app with sudo and it works fine in System Proxy mode. However it doesn't work in VPN mode at all. Not sure what's wrong with tun on mac. Any ideas how to fix?
