### ISSUE TITLE
Error Report: Issue Running 'hiddfy' on Fedora Linux 38 (KDE Plasma) - Service Startup Error

### ISSUE THREAD

**Issue by MohsenBg** [hiddify/hiddify-next#223]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

# Error Report: Issue Running 'hiddfy next' on Fedora Linux 38 (KDE Plasma) - Service Startup Error

I encountered an issue while attempting to run "hiddfy next." Upon clicking the Tap to Connect button, I received the following error message:

### Error Message
 Service startup error
initialize inbound/mixed[mixed-in]: set system proxy: execute (/usr/bin/ su) su - Bagheri -c dbus-send --type=signal /K10/Scheduler org.kde.KIO.SchedulerseparseSlaveConfiguration string:": exit status 1

![Screenshot_20231202_122120](https://github.com/hiddify/hiddify-next/assets/84536899/24fe7f69-4ed5-4091-9c12-e9edef7315db)

## System Details:

- **Operating System:** Fedora Linux 38 (KDE Plasma) x86_64
- **Kernel:** 6.6.2-101.fc38.x86_64
- **Shell:** zsh 5.9
- **Desktop Environment:** Plasma 5.27.9
- **Window Manager:** KWin
- **Terminal:** alacritty

### Steps to Reproduce:

1. Start hiddfy using the appimage with sudo.
2. Add my configuration to hiddfy next.
3. Change hiddfy next connection to VPN mode.
4. Click to tap the connection button and encounter an error.

### Version

0.11.1

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by MohsenBg** [comment]
Error Report: Issue Running 'hiddfy' on Fedora Linux 38 (KDE Plasma) - Service Startup Erro

**Comment by bamalt** [comment]
I have the same problem in hiddify-next v. 0.14.0 dev

Operating System: Ubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-14-generic (64-bit)
Graphics Platform: X11


 `[ConnectionNotifier] connection status: CONNECTION FAILURE: ConnectionFailure.unexpected(error: initialize inbound/mixed[mixed-in]: set system proxy: execute (/usr/bin/su) su - bamalt -c dbus-send --type=signal /KIO/Scheduler org.kde.KIO.Scheduler.reparseSlaveConfiguration string:'': exit status 1, stackTrace: null)`

**Comment by lymanjre** [comment]
Pls use RPM package. it should be solved

**Comment by gevera** [comment]
It was not solved. Just installed rpm package, Getting the same error

**Comment by RustLover2910** [comment]
Yep, getting the exact same error while executing it under administrator mode under KDE plasma fedora 40

**Comment by oxxxxxy** [comment]
Yep, same...

**Comment by oxxxxxy** [comment]
ERROR[0000] initialize inbound/mixed[mixed-in]: set system proxy: execute (/usr/bin/su) su - user0k -c dbus-send --type=signal /KIO/Scheduler org.kde.KIO.Scheduler.reparseSlaveConfiguration string:'': exit status 1

**Comment by oxxxxxy** [comment]
same error on the .appimage
same error on the .deb package
