### ISSUE TITLE
Wrong windows portable release file?

### ISSUE THREAD

**Issue by azhuge233** [hiddify/hiddify-next#258]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Both windows portable release file in version 0.12.1 and 0.12.0 are significantly smaller than 0.11.1.
It only has a single `.exe` file without all the other `.dll` files back in version 0.11.1, and this causes protable hiddify unusable.

### Reproduce the Bug

1. Download the latest windows portable `.zip`
2. Decompress it
3. Run `HiddifyNext.exe`
4. Cannot find dll errors came up

### Version

v.0.12.1

### Platform/OS

Windows

### Additional Context

![Snipaste_2023-12-22_09-34-13](https://github.com/hiddify/hiddify-next/assets/17763056/2513c49b-b45f-4e81-9332-0205333b13c9)
![Snipaste_2023-12-22_09-34-27](https://github.com/hiddify/hiddify-next/assets/17763056/d698b26c-2130-479e-8456-83b9453c9191)

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by RayWangQvQ** [comment]
same

**Comment by star2056** [comment]
Same here, I'm also using portable v0.11.1, checking update and found this bug.

**Comment by Abolfazl74** [comment]
no update on this?

**Comment by drw2005** [comment]
portable不能用啊，什么情况？

**Comment by problematicconsumer** [comment]
Fixed, new version will soon be released with portable version.

**Comment by drw2005** [comment]
> Fixed, new version will soon be released with portable version.

HiddifyNext.exe - 无法找到入口
---------------------------
无法定位程序输入点 SetUnhandledExceptionFilter 于动态链接库 api-ms-win-core-errorhandling-l1-1-1.dll 上。 

缺少好多链接库

**Comment by azhuge233** [comment]
> Fixed, new version will soon be released with portable version.


Yes, can confirm that the portable version 0.12.3 is still not able to run with all the `.dll` files back.
Double click `HiddifyNext.exe`, nothing happens.
