### ISSUE TITLE
install on linux deepin encountered an error

### ISSUE THREAD

**Issue by manzourimahdi** [hiddify/hiddify-next#450]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

when run appImage got this error:

./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hiddify)
./hiddify: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_hiddifyyOBLj/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_hiddifyyOBLj/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_hiddifyyOBLj/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by usr/lib/libgcc_s.so.1)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libgcc_s.so.1)

### Reproduce the Bug

just run appImage

### Version

v0.14.20

### Platform/OS

Linux

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by hsh9544** [comment]
This is solved in 0.15.6. Also a duplicate of #78.

**Comment by manzourimahdi** [comment]
now app version 0.15.6 installed successfuly but in run i got this error:
hiddify: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)

**Comment by manzourimahdi** [comment]
> This is solved in 0.15.6. Also a duplicate of #78.

now app version 0.15.6 installed successfuly but in run i got this error:
hiddify: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/share/hiddify/lib/libsqlite3_flutter_libs_plugin.so)


this is last version of glibc on deepin 20:
glibc 2.28.21-1+deepin-1

**Comment by MiangChen** [comment]
I meet the same problem when running ./Hiddify-Linux-x64.AppImage on Linux:

Error:
```
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hiddify)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_HiddifjYNnqz/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_HiddifjYNnqz/lib/libsqlite3_flutter_libs_plugin.so)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libstdc++.so.6)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by usr/lib/libgcc_s.so.1)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libgcc_s.so.1)
./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libresolv.so.2)
```

**Comment by MiangChen** [comment]
> I meet the same problem when running ./Hiddify-Linux-x64.AppImage on Linux:
> 
> Error:
> 
> ```
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./hiddify)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_HiddifjYNnqz/lib/libsqlite3_flutter_libs_plugin.so)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_HiddifjYNnqz/lib/libsqlite3_flutter_libs_plugin.so)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by usr/lib/libstdc++.so.6)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by usr/lib/libstdc++.so.6)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libstdc++.so.6)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by usr/lib/libgcc_s.so.1)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libgcc_s.so.1)
> ./hiddify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by usr/lib/libresolv.so.2)
> ```

I use 'ldd --version' to check the GLIBC version on my Linux:
```
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.14) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
```

**Comment by lymanjre** [comment]
This is fixed

**Comment by MasoudHD** [comment]
This issue exists even in newer versions. I tested on Ubuntu 24 and it works fine but in Debian 11 it is not fixed.

**Comment by ikarus-stv** [comment]
I try to install app on Ubuntu 20.04, error occurs.

**Comment by YustasDev** [comment]
> I try to install app on Ubuntu 20.04, error occurs.

same thing
